version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - appnet

  frontend:
    build: ./frontend
    depends_on:
      - backend
    deploy:
      replicas: 3
    networks:
      - appnet
    # Remove this line 👇 (or comment it out)
    # ports:
    #   - "3000:80"

networks:
  appnet:
